src/main/java/au/edu/usyd/domain/ShoppingCar.java
package au.edu.usyd.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "shoppingcar")
public class ShoppingCar {

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @Column(name = "bookid")
    private int bookid;
    
    @Column(name = "buyerid")
    private int buyerid;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getBookId() {
        return bookid;
    }

    public void setBookId(int bookid) {
        this.bookid = bookid;
    }
    
    public int getBuyerId() {
        return buyerid;
    }

    public void setBuyerId(int buyerid) {
        this.buyerid = buyerid;
    }
    
}

src/main/java/au/edu/usyd/domain/ShoppingCarInfo.java
package au.edu.usyd.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "shoppingcarinfo")
public class ShoppingCarInfo {
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;
   
    @Column(name = "bookname")
    private String bookname;
    
    @Column(name = "price")
    private double price;

    @Column(name = "place")
    private String place;
    
    @Column(name = "user")
    private int user;
    
    @Column(name = "photo")
    private String photo;
    
    @Column(name = "sellername")
    private String sellername;
    
    @Column(name = "buyerid")
    private int buyerid;
    
    @Column(name = "rating")
    private int rating;
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getBookName() {
        return bookname;
    }

    public void setBookName(String bookname) {
        this.bookname = bookname;
    }
    
    public double getPrice() {
        return price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    
    public int getUser() {
        return user;
    }
    
    public void setUser(int user) {
        this.user = user;
    }
    
    public String getPhoto() {
        return photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    
    public String getPlace() {
        return place;
    }

    public void setPlace(String place) {
        this.place = place;
    }
    
    public String getSellerName() {
        return sellername;
    }

    public void setSellerName(String sellername) {
        this.sellername = sellername;
    }

    public int getBuyerId() {
        return buyerid;
    }

    public void setBuyerId(int buyerid) {
        this.buyerid = buyerid;
    }
    
    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }
    
}

src/main/java/au/edu/sydney/controller/BookInfoController.java
package au.edu.usyd.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import au.edu.usyd.controller.BookInfoController;
import au.edu.usyd.dao.AlbumDao;
import au.edu.usyd.dao.BookDao;
import au.edu.usyd.dao.ShoppingCarDao;
import au.edu.usyd.dao.ShoppingCarInfoDao;
import au.edu.usyd.dao.UserDao;
import au.edu.usyd.domain.Album;
import au.edu.usyd.domain.Book;
import au.edu.usyd.domain.ShoppingCar;
import au.edu.usyd.domain.ShoppingCarInfo;
import au.edu.usyd.domain.User;

@Controller
@Transactional
public class BookInfoController {
	private int BuyerId;
	private ShoppingCarInfo shoppingcarinfoglobal = new ShoppingCarInfo(); 
	private ArrayList<Integer> ShoppingCarBookId = new ArrayList();
	
	//登陆后访问和无登录访问
	@RequestMapping(value = "/GET/bookinfo/{buyerId}/{bookId}", method = RequestMethod.GET)
	public String getBookInfoWithBuyer(@PathVariable("buyerId")Integer buyerId,@PathVariable("bookId")Integer bookId, Locale locale, Model model){
		BuyerId=buyerId;
	    model.addAttribute("bookId", bookId);
	    model.addAttribute("buyerId", buyerId);
		return "product";
	}

	@RequestMapping(value = "/GET/bookinfo/{bookId}", method = RequestMethod.GET)
	public String getBookInfoWithoutBuyer(@PathVariable("bookId")Integer bookId, Locale locale, Model model){
	    model.addAttribute("bookId", bookId);
		return "product";
	}
	
	//登录后访问和无登录加入购物车
	@Autowired
	ShoppingCarDao shopingcarDao;
	
	@RequestMapping(value = "/POST/shoppingcar/{buyerId}/{bookId}", method = RequestMethod.GET)
	public String addShoppingCarWithBuyer (@PathVariable("buyerId")Integer buyerId, @PathVariable("bookId")Integer bookId, Locale locale, Model model){
	    
		ShoppingCar shoppingcar = new ShoppingCar();
		shoppingcar.setBookId(bookId);
		shoppingcar.setBuyerId(buyerId);
	    
	    shopingcarDao.saveShoppingCar(shoppingcar);
	    model.addAttribute("buyerId", buyerId);
	    
	    return "afteraddshopingcar";
	}
	
	@RequestMapping(value = "/POST/shoppingcar/{bookId}", method = RequestMethod.GET)
	public String addShoppingCarWithoutBuyer (@PathVariable("bookId")Integer bookId, Locale locale, Model model){
		return "login";
	}
	
	//进入购物车
	@Autowired
	BookDao bookDao;
	
	@Autowired
	UserDao userDao;
	
	@Autowired
	AlbumDao albumDao;
	
	@Autowired
	ShoppingCarInfoDao shoppingcarinfoDao;
	
	@RequestMapping(value = "/GET/shoppingcarinfo/{buyerId}", method = RequestMethod.GET)
	public String getShoppingCarInfo(@PathVariable("buyerId")Integer buyerId, Locale locale, Model model){
		
		List<ShoppingCar> shoppingcar = shopingcarDao.loadShoppingCarBuyerId(buyerId);

		ArrayList<ShoppingCarInfo> infolist= new ArrayList<ShoppingCarInfo>();
		
		ArrayList<Integer> ShoppingCarBookIdlocal = new ArrayList();
		for(int i=0; i<shoppingcar.size();i++ ){
			
		int shoppingcarid = shoppingcar.get(i).getId();
		System.out.println(shoppingcarid);
		
		int bookid = shoppingcar.get(i).getBookId();
		Book book = bookDao.loadBook(bookid);
		
		ShoppingCarBookIdlocal.add(bookid);
		
		int userid = book.getUserId();
		User user = userDao.loadUser(userid);
		
		int albumid = book.getAlbumId();
		Album album = albumDao.loadAlbum(albumid);
		
		ShoppingCarInfo shoppingcarinfo = new ShoppingCarInfo();

		try{
		shoppingcarinfo.setId(shoppingcarid);
		shoppingcarinfo.setBookName(book.getBookName());
		shoppingcarinfo.setPrice(book.getPrice());
		shoppingcarinfo.setPlace(book.getPlace());
		shoppingcarinfo.setSellerName(user.getUserName());
		shoppingcarinfo.setBuyerId(buyerId);
		shoppingcarinfo.setPhoto(album.getUrl());

		
		infolist.add(shoppingcarinfo);
		shoppingcarinfoDao.saveShoppingCarInfo(shoppingcarinfo);
		}catch(Exception e){

			//System.out.println("Faile to load shppingcar");
		}
		

		
		//System.out.println(infolist);
		System.out.println(book.getBookName());
		}
		
		ShoppingCarBookId=ShoppingCarBookIdlocal;
		
		model.addAttribute("shoppingcar", infolist);
		model.addAttribute("buyerId", buyerId);
		
		return "cart";
	}
	
	
	@Autowired
	ShoppingCarInfoDao shoppingcarinfoDao2;
	@RequestMapping(value = "/DELETE/ShoppingCarItems/{buyerId}", method = RequestMethod.GET)
	public String shoppingcardelete(Locale locale, Model model, @RequestParam("orderID") int theId, @PathVariable("buyerId")Integer buyerId) {
		//logger.info("Welcome list all order record: {}.", locale);
				
		shoppingcarinfoDao2.deleteShoppingCarInfo(theId);
		
		List<ShoppingCarInfo> shoppingcar = shoppingcarinfoDao2.loadShoppingCarInfoBuyerId(buyerId);
		
		model.addAttribute("shoppingcar", shoppingcar);
		
		return "cart";
	}
	
	
	
	@Autowired
	BookDao bookDao2;
	@RequestMapping(value = "/POST/agreeshoppingcar/{buyerId}", method = RequestMethod.GET)
	public String agreeShoppingCar (@PathVariable("buyerId")Integer buyerId, Locale locale, Model model){
		for(int i=0; i<ShoppingCarBookId.size();i++ ){
			int bookid = ShoppingCarBookId.get(i);
			Book book = bookDao.loadBook(bookid);
		    book.setBookState("off");
		    bookDao2.updateBook(book);
		}
		
		model.addAttribute("buyerId", buyerId);
        return "Agree";
	}
	
	
	
	
}

src/main/java/au/edu/sydney/controller/HomeController.java
package au.edu.sydney;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import org.hibernate.Criteria;
import org.hibernate.Query;
import org.hibernate.SessionFactory;
import org.hibernate.criterion.Expression;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import au.edu.sydney.dao.AlbumDao;
import au.edu.sydney.dao.BookDao;
import au.edu.sydney.dao.PersonDao;
import au.edu.sydney.dao.TypeDao;
import au.edu.sydney.domain.Album;
import au.edu.sydney.domain.Book;
import au.edu.sydney.domain.Person;
import au.edu.sydney.domain.Type;
import net.sf.json.JSONObject;
import net.sf.json.JsonConfig;
import net.sf.json.util.CycleDetectionStrategy;

/**
 * Handles requests for the application home page.
 */
@Controller
@Transactional
public class HomeController {
	
	private static final Logger logger = LoggerFactory.getLogger(HomeController.class);
	
	/**
	 * Simply selects the home view to render by returning its name.
	 */
	AlbumDao albumDao;
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		logger.info("Welcome home! The client locale is {}.", locale);
		List<Book> fourBooks = bookDao4.loadFourBooks();
		int book1_id=fourBooks.get(0).getId();
		int book2_id=fourBooks.get(1).getId();
		int book3_id=fourBooks.get(2).getId();
		int book4_id=fourBooks.get(3).getId();
		model.addAttribute("book1_id",book1_id);
		model.addAttribute("book2_id",book2_id);
		model.addAttribute("book3_id",book3_id);
		model.addAttribute("book4_id",book4_id);
/*		int book1_url=fourBooks.get(0).getId();
		Album book1_album = albumDao.loadAlbum(book1_url);
		model.addAttribute("book1_url",book1_album.getUrl());*/
		return "home";
	}
	
	//test object
	@Autowired
	BookDao bookDao;
	@RequestMapping(value = "/getdata", method = RequestMethod.GET)
	@ResponseBody
	public Book getBookInfo(Locale locale) {
		logger.info("Welcome home! The client locale is {}.", locale);
		Book book = bookDao.loadBook(1);
		return book;
	}
	
	//get type list
	@Autowired
	TypeDao typeDao;
	@RequestMapping(value = "/getTypeList", method = RequestMethod.GET)
	@ResponseBody
	public List<Type> getTypeList() {
		List<Type> type = typeDao.loadTypeList();
		return type;
	}
	
	//get book list
	@Autowired
	BookDao bookDaoList;
	@RequestMapping(value = "/getBookList", method = RequestMethod.GET)
	@ResponseBody
	public List<Book> getBookList() {
		List<Book> book = bookDaoList.loadBookList();
		return book;
	}
	
	//get 4 books
	@Autowired
	BookDao bookDao4;
	@RequestMapping(value = "/getFourBooks", method = RequestMethod.GET)
	@ResponseBody
	public List<Book> getFourBooks() {
		List<Book> fourBooks = bookDao4.loadFourBooks();
		return fourBooks;
	}
	
	@RequestMapping(value = "/category", method = RequestMethod.GET)
	public String category() {	
		return "category";
	}
	
	@RequestMapping(value = "/jdbcAdd", method = RequestMethod.GET)
    public String jdbcAdd(Locale locale, Model model) {
        
        // JDBC driver name and database URL
        String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
        String DB_URL = "jdbc:mysql://localhost/elec5619";

        //  Database credentials
        String USER = "root"; // 
        String PASS = "root";
        
        Connection conn = null;
        PreparedStatement preparedStatement = null;
        try{
           //Register JDBC driver
           Class.forName("com.mysql.jdbc.Driver");

           //Open a connection
           System.out.println("Connecting to database...");
           conn = DriverManager.getConnection(DB_URL,USER,PASS);
           
           String insertTableSQL = "INSERT INTO employee (id, age, first, last) VALUES (?,?,?,?)";
           
           preparedStatement = conn.prepareStatement(insertTableSQL);
           preparedStatement.setInt(1, 1);
           preparedStatement.setInt(2, 25);
           preparedStatement.setString(3, "Test");
           preparedStatement.setString(4, "Name");

           // execute insert SQL statement
           preparedStatement.executeUpdate();
           System.out.println("Record is inserted into employee table!");
           
           //Clean-up environment
           preparedStatement.close();
           conn.close();
        }catch(SQLException se){
           //Handle errors for JDBC
           se.printStackTrace();
        }catch(Exception e){
           //Handle errors for Class.forName
           e.printStackTrace();
        }finally{
           try{
              if(preparedStatement!=null)
                  preparedStatement.close();
           }catch(SQLException se2){
           }
           try{
              if(conn!=null)
                 conn.close();
           }catch(SQLException se){
              se.printStackTrace();
           }
        }

        return "home";
    }
	
	@Autowired
	SessionFactory sessionFactory;
	@RequestMapping(value = "/hibernateAdd", method = RequestMethod.GET)
	public String hibernateAdd(Locale locale, Model model) {
		Person p = new Person();
	    p.setAge(20);
	    p.setFirst("FirstName");
	    p.setLast("lastName");
	        
	    sessionFactory.getCurrentSession().save(p);
	    return "home";
	}
	
	@Autowired
	PersonDao personDao;
	@RequestMapping(value = "/hibernateDaoAdd", method = RequestMethod.GET)
    public String hibernateDaoAdd(Locale locale, Model model) {
        Person p = new Person();
        p.setAge(20);
        p.setFirst("FirstName");
        p.setLast("lastName");

        personDao.savePerson(p);
        
        return "home";
    }
}

src/main/webapp/WEB-INF/views/Map.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
    <style>
       #map {
        height: 700px;
        width: 100%;
       }
    </style>
</head>
<body>





<div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: -33.886549, lng: 151.190389};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqBgUdlz6mpZilF7p5HbIv6kEOpAIz7-0&callback=initMap">
    </script>




</body>
</html>

src/main/webapp/WEB-INF/views/cart.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<link rel="stylesheet" type="text/css" href="/usyd/resources/main.css" />
<title>iCart HTML Version</title>
</head>
<body>
<div class="menu">
<ul>
<li style="width:0px;"><a></a></li>
<li><a href="/usyd/home/${buyerId}" class="home">Home</a></li>

<li class="active"><a href="/usyd/GET/shoppingcarinfo/${buyerId}" class="cart">Transaction History</a></li>

<li style="float:right;"><a href="/usyd/user/signin" class="login">Login</a></li>
<li style="float:right;"><a href="/usyd/user/signup" class="register">Register</a></li>
</ul>
</div>

<div style="width:1000px;margin:0 auto;">
    <div id="cart">

    <div class="content"></div>
  </div>  
	<div id="search">
    <div class="button-search"></div>
        <input type="text" name="filter_name" value="Search"  onkeydown="this.style.color = '#888';" />
      </div>

</div>

<div class="header">
<div class="logo_img"></div></div>

<div id="menu">
<ul>  
<li><a href="categories.html">Desktops</a>
<div>        
<ul>	
<li><a href="default.htm">PC (0)</a></li>
<li><a href="default.htm">Mac (1)</a></li>
</ul>
</div>
</li>
<li><a href="categories.html">Laptops &amp; Notebooks</a>   	
<div>
<ul>	
<li><a href="default.htm">Macs (0)</a></li>
<li><a href="default.htm">Windows (0)</a></li>
</ul>
</div>
</li>
<li><a href="categories.html">Components</a>
<div>
<ul>	
<li><a href="default.htm">Mice and Trackballs (0)</a></li>
<li><a href="default.htm">Monitors (2)</a></li>
<li><a href="default.htm">Printers (0)</a></li>
<li><a href="default.htm">Scanners (0)</a></li>
<li><a href="default.htm">Web Cameras (0)</a></li>
</ul>
</div>
</li>
<li><a href="categories.html">Software</a></li>
<li><a href="categories.html">Phones &amp; PDAs</a></li>
<li><a href="categories.html">Cameras</a></li>
</ul>
</div>




<div style="width:1000px;margin: 0 auto;margin-top:10px;">
<div class="linktree">
        <a href="#">Home</a>
         &raquo; <a href="#">Shopping Cart</a>
    </div>
<h1 style="margin-top:-10px;">Shopping Cart&nbsp;</h1>


<br>
     <form action="#" method="post" id="basket">
      <div class="cart-info">
        <table>

            <tr>
              <td class="remove">Remove</td>
              <td class="image">Image</td>
              <td class="name">Book Name</td>
              <td class="model">Book Price</td>
              <td class="quantity">Transaction Place</td>
              <td class="price">Seller Name</td>
            </tr>

				<c:forEach var="newshoppingcar" items="${shoppingcar}">
				
				
				
				<c:url var="DeleteLink" value="/DELETE/ShoppingCarItems/${buyerId}">
					 	<c:param name="orderID" value="${newshoppingcar.id}"/>
				</c:url>
				

				

				<tr>
				<td><a href="${DeleteLink}">Delete</a></td>
				<td><img src="${newshoppingcar.photo}" alt="iMac" /></td>
				<td>${newshoppingcar.bookName}</td>
				<td>${newshoppingcar.price}</td>
				<td>${newshoppingcar.place}</td>
				<td>${newshoppingcar.sellerName}</td>				
				<td></td>
				
				
				
				</tr>
				</c:forEach>

        </table>
      </div>
    </form>

    <div class="buttons">
      <div class="right"><a href="/usyd/POST/agreeshoppingcar/${buyerId}" class="button"><span>Agree</span></a></div>
      <div class="center"><a href="/usyd/home/${buyerId}" class="button" style="width:120px;"><span>Continue Shopping</span></a></div>
    </div>

</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="icart-footer">
<div class="icart-footer-top">
	<div style="width:1000px; margin:0 auto;">	
	</div>
</div>
<div class="icart-footer-container">
	<div class="column_footer" style="width:350px;">
		<h3>About Us</h3>
		  Zhaohui Chang Shenghui wu Yuying Shao
	</div>
	
	<div class="column_footer">
		<h3>Customer Service</h3>
		<ul>
		<li><a href="#">About Us</a></li>
      		<li><a href="#">Delivery Information</a></li>
      		<li><a href="#">Privacy Policy</a></li>
      		<li><a href="#">Terms &amp; Conditions</a></li>
      		<li><a href="#">Contact Us</a></li>
      		<li><a href="#">Returns</a></li>
      		<li><a href="#">Site Map</a></li>
		</ul>
	</div>
	
	<div class="column_footer" style="width:150px;">
		<h3>Extras</h3>
		<ul>
      		<li><a href="#">Brands</a></li>
      		<li><a href="#">Gift Vouchers</a></li>
      		<li><a href="#">Affiliates</a></li>
      		<li><a href="#">Specials</a></li>
		</ul>
	</div>	
	<div class="column_footer" style="width:150px;">
		<h3>My Account</h3>
		<ul>
      		<li><a href="#">My Account</a></li>
      		<li><a href="#">Order History</a></li>
      		<li><a href="#">Wish List</a></li>
      		<li><a href="#">Newsletter</a></li>
		</ul>
</div>
		
	<div class="column_footer" style="margin-right:0px;">
		<h3>Social</h3>
		<ul class="social">
			<li class="twitter"><a href="../../twitter.com/twitter">Twitter Username</a></li>
			<li class="facebook"><a href="../../facebook.com/Username/default.htm">Facebook</a></li>
			<li class="rss"><a href="#">RSS Feed</a></li>
		</ul>				
	</div>		
	<div class="clearfix"></div>
	</div>		
	<div class="icart-footer-bottom">
		<div style="width:1000px; margin:0 auto;">				
		<div class="icart-logo-footer"><a href="index.php"><img src="images/logo-footer.png" alt="Footer Logo"></a></div>	
			<ul>
			<li style="float:right;padding-top:10px;list-style:none;">&copy; Copyright &copy; 2013.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></li>
			</ul>		
		<div class="clearfix"></div>
		</div>

</div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/views/publish.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page session="false" %>

<!DOCTYPE html>

<html>

<head>
	<title>Publish</title>
</head>

<body>
<P class="text-center">
<b>Create a New Account!<br></b>

	<i>${error_infor}</i>
	<!-- creat the table for sign up -->
	<form action="/sydney/user/processSubmit">
		<br><br>
		<table>
			<tr>
				<td>User Name*:<br><br></td>
				<td><input type="text" name="userName" required><br><br></td>
			</tr>
			<tr>
				<td>Password*:<br><br></td>
				<td><input type="password" name="userPassword" required><br><br></td>
			</tr>
			<tr>
				<td>Email*:<br><br></td>
				<td><input type="email" name="userEmail" required><br><br></td>
			</tr>
			<tr>
				<td>Telephone*:<br><br></td>
				<td><input type="text" name="userPhone" required><br><br></td>
			</tr>
			<tr>
				<td>School*:<br><br></td>
				<td><input type="text" name="userSchool" required><br><br></td>
			</tr>
			<tr>
				<td>Sid*:<br><br></td>
				<td><input type="text" name="userSid" required><br><br></td>
			</tr>
			
			<tr>
				<td><input type="submit" value="Submit" class="btn btn-primary"><br><br></td>
				</td>
			</tr>
		</table>
	</form>
		
		<br><br>

 </P>
</body>
</html>

src/main/webapp/WEB-INF/views/rating.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
Rating
</body>
</html>

src/main/webapp/WEB-INF/views/start.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
<script src="js/BookInfoAjax.js"></script>
</head>
<body>
<p>Start</p>
		    <div>
		     		Id: <input type="text" id ="bookId">
		       <input type="button" id="btnPass" value="Go" onclick="location='http://localhost:3000/usyd/SHOW/bookinfo/1'"/>
		    </div> 
</body>
</html>